package com.resumeanalyser.feedback;

import com.resumeanalyser.recommendation.Recommendation;
import com.resumeanalyser.skillvector.SkillVector;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import java.time.Instant;
import java.util.UUID;

/**
 * A user's "helpful" / "not helpful" verdict on one specific {@link Recommendation}.
 * This is the raw signal the EMA skill-vector update is computed from. It also
 * records exactly which {@link SkillVector} version was active at the moment the
 * feedback was given, so a later weight change can always be traced back to the
 * feedback that caused it.
 */
@Entity
@Table(name = "feedback")
@Getter
@Setter
public class Feedback {

    /** Primary key, generated by the database on insert. */
    @Id
    @GeneratedValue
    private UUID id;

    /** The specific recommendation this feedback is about. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "recommendation_id", nullable = false)
    private Recommendation recommendation;

    /**
     * The skill-vector version that was active when this feedback was given.
     * Nullable so old feedback still survives even if that specific version
     * is later purged.
     */
    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "skill_vector_version_id")
    private SkillVector skillVectorVersion;

    /** True if the user found the recommendation helpful, false otherwise. */
    @Column(nullable = false)
    private boolean helpful;

    /** When this feedback was submitted. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt = Instant.now();
}
