package com.resumeanalyser.account;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import java.time.Instant;
import java.util.UUID;

/**
 * A registered account holder: the person who logs in, uploads resumes, and
 * receives recommendations. This is the identity/credential record that the
 * `auth` module authenticates against — `account` owns the data, `auth`
 * owns the login mechanics that operate on it.
 */
@Entity
@Table(name = "users")
@Getter
@Setter
public class User {

    /** Primary key, generated by the database on insert. */
    @Id
    @GeneratedValue
    private UUID id;

    /** The user's login identifier. Must be unique across all accounts. */
    @Column(nullable = false, unique = true, length = 320)
    private String email;

    /** Bcrypt hash of the user's password. The plaintext password is never stored or logged. */
    @Column(name = "password_hash", nullable = false, length = 255)
    private String passwordHash;

    /**
     * The user's access level (USER / PREMIUM_USER / ADMIN), used for role-based access control.
     * Every new account starts as USER; upgrading to PREMIUM_USER happens later, not at sign-up.
     */
    @Enumerated(EnumType.STRING)
    @Column(nullable = false, length = 20)
    private UserRole role = UserRole.USER;

    /** When this account was created. Set once and never changed afterward. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt = Instant.now();
}
