package com.resumeanalyser.skillvector;

import com.resumeanalyser.recommendation.Role;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import java.time.Instant;
import java.util.UUID;

/**
 * One versioned weight for a single (role, skill) pair. This is the core of the
 * "temporal EMA skill-vector" mechanism: instead of updating a weight in place,
 * every recalculation inserts a brand new row and marks the old one no longer
 * current, so the full history of how a skill's importance to a role has
 * changed over time is always preserved and queryable.
 */
@Entity
@Table(name = "skill_vectors")
@Getter
@Setter
public class SkillVector {

    /** Primary key, generated by the database on insert. */
    @Id
    @GeneratedValue
    private UUID id;

    /** The role this weighted skill belongs to. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "role_id", nullable = false)
    private Role role;

    /** The skill's canonical name, matching the skill taxonomy used elsewhere in the system. */
    @Column(nullable = false)
    private String skill;

    /**
     * This skill's current importance to the role, updated by an exponential
     * moving average: {@code new = alpha * signal + (1 - alpha) * old}.
     */
    @Column(nullable = false)
    private double weight;

    /** When this specific weight value was written -- never updated after insert. */
    @Column(name = "version_timestamp", nullable = false)
    private Instant versionTimestamp = Instant.now();

    /**
     * True for exactly one row per (role, skill) at any given time -- the version
     * that {@code /match} actually reads. Older versions for the same (role, skill)
     * have this flipped to false rather than being deleted.
     */
    @Column(nullable = false)
    private boolean current = true;
}
