package com.resumeanalyser.resume;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import org.hibernate.annotations.JdbcTypeCode;
import org.hibernate.type.SqlTypes;
import java.util.List;
import java.util.UUID;

/**
 * The structured data extracted from one {@link Resume} by the ML parsing
 * service -- name, contact details, skills, work history, and education.
 * There is exactly one of these per resume version (1:1). Mirrors the
 * ML service's {@code ResumeProfile}/{@code ExperienceEntry}/{@code EducationEntry}
 * Pydantic models field-for-field, so the two sides of the system agree on shape.
 */
@Entity
@Table(name = "parsed_profiles")
@Getter
@Setter
public class ParsedProfile {

    /** Primary key, generated by the database on insert. */
    @Id
    @GeneratedValue
    private UUID id;

    /** The resume version this profile was extracted from. */
    @OneToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "resume_id", nullable = false, unique = true)
    private Resume resume;

    /** Candidate's full name, as extracted by the parser. Empty string if not found. */
    @Column(nullable = false)
    private String name = "";

    /** Contact email, as extracted by the parser. Empty string if not found. */
    @Column(nullable = false)
    private String email = "";

    /** Contact phone number, as extracted by the parser. Empty string if not found. */
    @Column(nullable = false)
    private String phone = "";

    /** Raw skill names as extracted by the parser -- not yet normalized against the skill taxonomy. */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(nullable = false)
    private List<String> skills;

    /** Work history entries, in the order the parser found them. */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(nullable = false)
    private List<ExperienceEntry> experience;

    /** Education entries, in the order the parser found them. */
    @JdbcTypeCode(SqlTypes.JSON)
    @Column(nullable = false)
    private List<EducationEntry> education;

    /**
     * One entry in a candidate's work history.
     *
     * @param title        job title
     * @param organization employer name
     * @param duration     free-text duration as written on the resume (e.g. "2022-2024"),
     *                     deliberately not parsed into start/end dates
     * @param description  free-text description of the role
     */
    public record ExperienceEntry(String title, String organization, String duration, String description) {}

    /**
     * One entry in a candidate's education history.
     *
     * @param degree      degree name (e.g. "B.S. Computer Science")
     * @param institution school/university name
     * @param year        free-text graduation year as written on the resume
     */
    public record EducationEntry(String degree, String institution, String year) {}
}
