package com.resumeanalyser.resume;

import com.resumeanalyser.account.User;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import java.time.Instant;
import java.util.UUID;

/**
 * One uploaded resume file, tracked by version. Every new upload creates a new
 * row with an incremented {@code version} rather than overwriting the previous
 * one (FR-1.5), so a user's full upload history is always retrievable. The
 * actual file bytes live in object storage; only a pointer to them ({@code fileRef}) is stored here.
 */
@Entity
@Table(name = "resumes", uniqueConstraints = @UniqueConstraint(columnNames = {"user_id", "version"}))
@Getter
@Setter
public class Resume {

    /** Primary key, generated by the database on insert. */
    @Id
    @GeneratedValue
    private UUID id;

    /** The account that uploaded this resume. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** Object-storage key/URL where the actual resume file lives; never the raw file bytes. */
    @Column(name = "file_ref", nullable = false, columnDefinition = "TEXT")
    private String fileRef;

    /** This upload's position in the user's upload history. Starts at 1 and only ever increases per user. */
    @Column(nullable = false)
    private int version;

    /** When this specific version was uploaded. */
    @Column(name = "uploaded_at", nullable = false, updatable = false)
    private Instant uploadedAt = Instant.now();
}
