package com.resumeanalyser.recommendation;

import com.resumeanalyser.account.User;
import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import java.time.Instant;
import java.util.UUID;

/**
 * One (user, role) match produced by an analysis run -- a snapshot of "this
 * user was {@code matchScore} similar to this role, at this point in time."
 * A new row is written on every analysis, so a user's match history/trend for
 * a given role can be reconstructed by querying all their rows over time.
 */
@Entity
@Table(name = "recommendations")
@Getter
@Setter
public class Recommendation {

    /** Primary key, generated by the database on insert. */
    @Id
    @GeneratedValue
    private UUID id;

    /** The account this recommendation was generated for. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "user_id", nullable = false)
    private User user;

    /** The role this recommendation points to. */
    @ManyToOne(fetch = FetchType.LAZY, optional = false)
    @JoinColumn(name = "role_id", nullable = false)
    private Role role;

    /** Cosine similarity between the candidate and the role, in the range [0.0, 1.0]. */
    @Column(name = "match_score", nullable = false)
    private double matchScore;

    /** When this recommendation was generated. */
    @Column(name = "created_at", nullable = false, updatable = false)
    private Instant createdAt = Instant.now();
}
