package com.resumeanalyser.recommendation;

import jakarta.persistence.*;
import lombok.Getter;
import lombok.Setter;
import java.util.UUID;

/**
 * A curated job role a candidate can be matched against (e.g. "Backend Software
 * Engineer"). This is the database-backed replacement for the static
 * {@code role_skills.json} file the ML service currently reads from.
 * Not to be confused with {@link com.resumeanalyser.account.UserRole}, which is
 * an account's access level, not a job title.
 */
@Entity
@Table(name = "roles")
@Getter
@Setter
public class Role {

    /** Primary key, generated by the database on insert. */
    @Id
    @GeneratedValue
    private UUID id;

    /** The role's display name, e.g. "Backend Software Engineer". Unique across all roles. */
    @Column(nullable = false, unique = true)
    private String title;

    /** Free-text description of the role, shown on dashboards. Empty until an admin fills it in. */
    @Column(nullable = false, columnDefinition = "TEXT")
    private String description = "";
}
